- name: Obter e armazenar o número de changes de um job no Ansible Automation Controller
  hosts: localhost
  gather_facts: False
  vars:
    job_id:  # essa informacao vem do playbook de hardening
    ac_token: "YOUR_ACCESS_TOKEN_HERE"
  tasks:
    - name: Obter detalhes do job do Ansible Automation Controller
      uri:
        url: "https://student1.gr5j5.example.opentlc.com/api/v2/jobs/{{ job_id }}/"
        method: GET
        return_content: yes
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ac_token }}"
        validate_certs: no
      register: job_details

    - name: Armazenar o número de changes
      set_fact:
        changes_count: "{{ job_details.json.host_status_counts.changed | default(0) | int }}"

    - name: Mostrar o número de changes
      debug:
        msg: "O número de changes é {{ changes_count }}."

    - name: detalhes do job
      debug:
        msg: "Para mais detalhes sobre o Job acesso https://student1.gr5j5.example.opentlc.com/#/jobs/playbook/{{ job_id }}/output"

    - name: Get job events from API
      uri:
        url: "https://student1.gr5j5.example.opentlc.com/api/v2/jobs/{{ job_id }}/job_events/"
        method: GET
        return_content: yes
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ac_token }}"
      register: job_events
      when: changes_count | int > 0

    - name: Get job stdout from API
      uri:
        url: "https://student1.gr5j5.example.opentlc.com/api/v2/jobs/{{ job_id }}/stdout/?format=json"
        method: GET
        return_content: yes
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ac_token }}"
      register: job_stdout
      when: changes_count | int > 0

    - name: Debug parsed content
      debug:
        var: job_stdout.content

    - name: Create incident importantapp
     servicenow.itsm.incident:
       state: new
       short_description: "Diferença de configuração detectada"
       description:  "A automação identificou uma diferença na configuração importante nos equipamentos de rede. Para mais detalhes sobre o Job acesso https://student1.gr5j5.example.opentlc.com/#/jobs/playbook/{{ job_id }}/output"
       impact: high
       urgency: high 
     register: incident

    - name: set stats for incident
      set_stats:
        data:
          incident_record_number: "{{ incident.record.number }}"

    - name: debug for incident
      debug:
        msg: 
          - "{{ incident }}"
          - "{{ incident.record.number }}"