---
- name: Obter e armazenar o número de changes de um job no Ansible Automation Controller
  hosts: localhost
  gather_facts: False
  vars:
    job_id:  # essa informacao vem do playbook de hardening
    ac_token:
  tasks:
    - name: Obter detalhes do job do Ansible Automation Controller
      uri:
        url: "https://student1.gr5j5.example.opentlc.com/api/v2/jobs/{{ job_id }}/"
        method: GET
        return_content: yes
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ac_token }}"
        validate_certs: no
      register: job_details

    - name: Armazenar o número de changes
      set_fact:
        changes_count: "{{ job_details.json.host_status_counts.changed | default(0) }}"

    - name: Mostrar o número de changes
      debug:
        msg: "O número de changes é {{ changes_count }}."
