---
- name: Cisco IOS XE Hardening Configuration
  hosts: cisco
  gather_facts: no
  connection: network_cli
  vars:
    exec_timeout_min: 5
    exec_timeout_sec: 0
    loopback_ip: 192.168.1.1
    loopback_mask: 255.255.255.0
    memory_threshold_processor: 10
    memory_threshold_io: 10
    memory_reserve_critical: 5
    cpu_threshold_type: both
    cpu_rising_percentage: 80
    cpu_falling_percentage: 60
    cpu_threshold_interval: 60
    ntp_server: 172.16.1.5
    ntp_key_id: 5
    ntp_key: ciscotime
    community_string: "suaStringDeComunidade"  # Defina sua string de comunidade SNMP aqui


  tasks:
    - name: Configure EXEC Timeout
      cisco.ios.ios_config:
        lines:
          - exec-timeout {{ exec_timeout_min }} {{ exec_timeout_sec }}
        parents: "{{ item }}"
      loop:
        - line con 0
        - line vty 0 4

    - name: Enable TCP Keepalives In and Out
      cisco.ios.ios_config:
        lines:
          - service tcp-keepalives-in
          - service tcp-keepalives-out

    - name: Configure Management Loopback Interface
      cisco.ios.ios_config:
        lines:
          - ip address {{ loopback_ip }} {{ loopback_mask }}
        parents: interface Loopback0

    - name: Configure Memory Threshold Notifications
      ios_config:
        lines:
          - memory free low-watermark processor {{ memory_threshold_processor }}
          # Removido a linha para configurar memory free low-watermark io
          - memory reserve critical {{ memory_reserve_critical }}

    - name: Configure NTP with Authentication
      ios_ntp_global:
        server:
          - name: "{{ ntp_server }}"
            key_id: "{{ ntp_key_id }}"
            prefer: true
        authenticate: true
        authentication_keys:
          - id: "{{ ntp_key_id }}"
            algorithm: md5
            key: "{{ ntp_key }}"
        trusted_key: "{{ ntp_key_id }}"

