---
- name: Playbook to configure ansible controller for AAP Demo during Neotwking Workshop
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files: vars.yml

  tasks:
    - name: Job Templates
      ansible.controller.job_template:
        name: "{{item.name}}"
        controller_host: "{{host}}"
        controller_username: "{{username}}"
        controller_password: "{{password}}"
        project: "{{item.project}}"
        execution_environment: "{{item.execution_environment}}"
        inventory: "{{item.inventory}}"
        playbook: "{{item.playbook}}"
        credentials: "{{item.credentials}}"
        validate_certs: no
      loop: "{{templates}}"

    - name: Workshop Workflow
      ansible.controller.workflow_job_template:
        name: "Workshop Workflow"
        organization: "Red Hat network organization"
        state: present
        validate_certs: false
        controller_host: "{{host}}"
        controller_username: "{{username}}"
        controller_password: "{{password}}"
        survey_enabled: yes
        survey_spec: {
                        "description": "",
                        "name": "",
                        "spec": [
                            {
                                "choices": "",
                                "default": "",
                                "max": 1024,
                                "min": 0,
                                "new_question": true,
                                "question_description": "Please type into the text field the desired banner",
                                "question_name": "Please enter the banner text",
                                "required": true,
                                "type": "textarea",
                                "variable": "net_banner"
                            },
                            {
                                "choices": "login\nmotd",
                                "default": "login",
                                "max": 1024,
                                "min": 0,
                                "new_question": true,
                                "question_description": "Please choose an option",
                                "question_name": "Please enter the banner type",
                                "required": true,
                                "type": "multiplechoice",
                                "variable": "net_type"
                            }
                        ]}
  

    - name: Network Automation - Restore
      ansible.controller.workflow_job_template_node:
        identifier: Network Automation - Restore
        workflow: "Workshop Workflow"
        unified_job_template: Network Automation - Restore
        organization: "Red Hat network organization"
        state: present
        validate_certs: false
        controller_host: "{{host}}"
        controller_username: "{{username}}"
        controller_password: "{{password}}"

    - name: Network-User
      ansible.controller.workflow_job_template_node:
        identifier: Network-User
        workflow: "Workshop Workflow"
        unified_job_template: Network-User
        organization: "Red Hat network organization"
        state: present
        failure_nodes:
          - Network Automation - Restore
        validate_certs: false
        controller_host: "{{host}}"
        controller_username: "{{username}}"
        controller_password: "{{password}}"

    - name: Network-Banner
      ansible.controller.workflow_job_template_node:
        identifier: Network-Banner
        workflow: "Workshop Workflow"
        unified_job_template: Network-Banner
        organization: "Red Hat network organization"
        state: present
        failure_nodes:
          - Network Automation - Restore
        validate_certs: false
        controller_host: "{{host}}"
        controller_username: "{{username}}"
        controller_password: "{{password}}"

    - name: Backup network configuration
      ansible.controller.workflow_job_template_node:
        identifier: Backup network configuration
        workflow: "Workshop Workflow"
        unified_job_template: Backup network configurations
        organization: "Red Hat network organization"
        state: present
        success_nodes:
          - Network-Banner
          - Network-User
        validate_certs: false
        controller_host: "{{host}}"
        controller_username: "{{username}}"
        controller_password: "{{password}}"
